### ISSUE TITLE
assertClose() does not support float ranges

### ISSUE THREAD

**Issue by Moneil97** [electricimp/impUnit#17]
For example, if I want to assert that x is within 0.5 of y then I could do:

```squirrel
this.assertClose(x, y, 0.5);
```

The following will throw:
```squirrel
local x = 0;
local y = 1;
this.assertClose(x, y, 0.5);
```

But this will not:
```squirrel
local x = 0;
local y = 0.99;
this.assertClose(x, y, 0.5);
```

This is because assertClose() uses math.abs() which returns an integer
https://github.com/electricimp/impUnit/blob/3657c655d2c0defacf5b626fe89db3aced3e7cdc/src/ImpTestCase.nut#L119

so  ```math.abs(0 - 0.99) == 0```

Please consider replacing abs() with fabs() or having a separate function for it such as assertCloseFloat()

**Comment by Rahulvaman** [comment]
Pull request successfully merged and closed 
Merge pull request https://github.com/electricimp/impUnit/pull/19 from electricimp/idc_trial
